#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  agent.sdk.sidetree.mock:
    container_name: agent.sdk.sidetree.mock
    image: ${SIDETREE_MOCK_FIXTURE_IMAGE}:${SIDETREE_MOCK_FIXTURE_IMAGE_TAG}
    environment:
      - SIDETREE_MOCK_HOST=0.0.0.0
      - SIDETREE_MOCK_PORT=48326
      - SIDETREE_MOCK_DID_NAMESPACE=did:sidetree:test
    ports:
      - 48326:48326
    volumes:
      - ../keys/tls:/etc/sidetree/tls
    networks:
      - agent-sdk-rest-net

networks:
  agent-sdk-rest-net:
    external: true
