# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
trigger:
  - main
pr:
  - main
variables:
  GO_VERSION: 1.16
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: Checks
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          echo '//npm.pkg.github.com/:_authToken=${DOCKER_PASSWORD}' > ~/.npmrc
          echo '@hyperledger:registry=https://npm.pkg.github.com' >> ~/.npmrc
          echo '@trustbloc-cicd:registry=https://npm.pkg.github.com' >> ~/.npmrc
          echo '@trustbloc:registry=https://npm.pkg.github.com' >> ~/.npmrc
          make checks
        env:
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
        displayName: Run checks
  - job: UnitTest
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make unit-test
        displayName: Run unit test
      - script: bash <(curl https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN
        env:
          CODECOV_UPLOAD_TOKEN: $(CODECOV_UPLOAD_TOKEN)
        displayName: Upload coverage to Codecov

  - job: UnitTestWasm
    pool:
      vmImage: ubuntu-18.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - script: make unit-test-wasm
        displayName: Run unit test wasm

  - job: AgentRestAPTest
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          make rest-api-bdd
        displayName: Run agent REST API tests (docker)

  - job: AgentJSTest
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          source ci/version_var.sh
          echo '//npm.pkg.github.com/:_authToken=${DOCKER_PASSWORD}' > ~/.npmrc
          echo '@hyperledger:registry=https://npm.pkg.github.com' >> ~/.npmrc
          echo '@trustbloc-cicd:registry=https://npm.pkg.github.com' >> ~/.npmrc
          echo '@trustbloc:registry=https://npm.pkg.github.com' >> ~/.npmrc
          export npm_config_prefix=~/.npm-prefix
          echo '127.0.0.1 static-file-server-js' | sudo tee -a /etc/hosts
          make aries-js-bdd
        env:
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
        displayName: Run agent JS tests (npm)

  - job: Publish
    dependsOn:
      - Checks
      - UnitTest
      - UnitTestWasm
      - AgentJSTest
      - AgentRestAPTest
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 30
    steps:
      - template: azp-dependencies.yml
      - checkout: self
      - bash: |
          function logout {
            docker logout
          }
          trap logout EXIT
          git lfs install
          git lfs pull
          source ci/version_var.sh
          echo $DOCKER_PASSWORD | docker login ghcr.io --username $DOCKER_USER --password-stdin
          echo '//npm.pkg.github.com/:_authToken=${DOCKER_PASSWORD}' > ~/.npmrc
          echo '@hyperledger:registry=https://npm.pkg.github.com' >> ~/.npmrc
          echo '@trustbloc-cicd:registry=https://npm.pkg.github.com' >> ~/.npmrc
          echo '@trustbloc:registry=https://npm.pkg.github.com' >> ~/.npmrc
          make agent-server-docker
          docker tag ghcr.io/trustbloc/agent-sdk-server:latest ${AGENT_SDK_PKG}:${AGENT_SDK_TAG}
          docker push ${AGENT_SDK_PKG}:${AGENT_SDK_TAG}
          cd ./cmd/agent-js-worker
          sed -i 's/"version": "0.1.0"/"version": "'$NPM_PKG_TAG'"/g' package.json
          sed -i 's#"name": "@trustbloc/agent-sdk-web"#"name": "@'${NPM_PKG_NAME}'"#g' package.json
          sed -i 's#"url": "git://github.com/trustbloc/agent-sdk.git"#"url": "git://github.com/'${NPM_PKG_REPO}'.git"#g' package.json
          npm install
          npm publish
        env:
          DOCKER_PASSWORD: $(DOCKER_PASSWORD)
          DOCKER_USER: $(DOCKER_USER)
          NPM_PKG_TAG: $(NPM_PKG_TAG)
          NPM_PKG_NAME: $(NPM_PKG_NAME)
          NPM_PKG_REPO: $(NPM_PKG_REPO)
